### ISSUE TITLE
Issues with URL

### ISSUE THREAD

**Issue by frankpaul142** [kohenkatz/appqr#9]
I created a QR that gives me this url  "http://m.appqr.mobi/appqr?qr=1&androidmarket=https://play.google.com/store/apps/details?id=com.picknsave&hl=en_US&appstore=https://apps.apple.com/ec/app/picknsave/id1473554307"
but right now is not working, what can i do to re activate this QR

**Comment by kohenkatz** [comment]
I'm sorry I never saw this notification. This repository is not associated with the AppQR website, it is only a mirror of their code from when Google Code shut down.
